### ISSUE TITLE
Como usuario quiero poder registrarme para poder utilizar la aplicación.

### ISSUE THREAD

**Issue by ikerLopezZ** [ikerLopezZ/BSPQ-03_client#4]
#37

**Comment by CristinaAlonsoAstigarraga** [comment]
- Crear las ventanas para insertar datos registro - versión simple (elementos básicos)
- Crear ventana principal - versión simple (elementos básicos)
- Crear base de datos
- Crear perfiles (gestor, usuario/cliente y artista)
- Crear clases (gui, service locator, funcionalidad en el server)
